---
- name: install dependency
  apt: 
    name: "{{ item }}"
    state: present
  loop: 
    - apt-transport-https
    - ca-certificates
    - gnupg
    - curl
    - sudo

- name: install gcloud key
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add the repo
  apt_repository:
    repo: 'deb https://packages.cloud.google.com/apt cloud-sdk main'
    state: present

- name: install gcloud
  apt:
    name: google-cloud-cli
    state: present
    update_cache: yes

- name: install kubectl
  apt:
    name: kubectl
    state: present

- name: install gke-cloud-auth
  apt:
    name: google-cloud-sdk-gke-gcloud-auth-plugin
    state: present